require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")

require 'json'
podfile_properties = JSON.parse(File.read(File.join(__dir__, 'Podfile.properties.json'))) rescue {}

ENV['RCT_NEW_ARCH_ENABLED'] = podfile_properties['newArchEnabled'] == 'true' ? '1' : '0'
ENV['EX_DEV_CLIENT_NETWORK_INSPECTOR'] = podfile_properties['EX_DEV_CLIENT_NETWORK_INSPECTOR']

platform :ios, podfile_properties['ios.deploymentTarget'] || '15.1'
install! 'cocoapods',
  :deterministic_uuids => false

prepare_react_native_project!

target 'DribblingMadness' do
  use_expo_modules!

  if ENV['EXPO_USE_COMMUNITY_AUTOLINKING'] == '1'
    config_command = ['node', '-e', "process.argv=['', '', 'config'];require('@react-native-community/cli').run()"];
  else
    config_command = [
      'node',
      '--no-warnings',
      '--eval',
      'require(require.resolve(\'expo-modules-autolinking\', { paths: [require.resolve(\'expo/package.json\')] }))(process.argv.slice(1))',
      'react-native-config',
      '--json',
      '--platform',
      'ios'
    ]
  end

  config = use_native_modules!(config_command)

  use_frameworks! :linkage => podfile_properties['ios.useFrameworks'].to_sym if podfile_properties['ios.useFrameworks']
  use_frameworks! :linkage => ENV['USE_FRAMEWORKS'].to_sym if ENV['USE_FRAMEWORKS']

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => podfile_properties['expo.jsEngine'] == nil || podfile_properties['expo.jsEngine'] == 'hermes',
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :privacy_file_aggregation_enabled => podfile_properties['apple.privacyManifestAggregationEnabled'] != 'false',
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      :ccache_enabled => podfile_properties['apple.ccacheEnabled'] == 'true',
    )

    # This is necessary for Xcode 14, because it signs resource bundles by default
    # when building for devices.
    installer.target_installation_results.pod_target_installation_results
      .each do |pod_name, target_installation_result|
      target_installation_result.resource_bundle_targets.each do |resource_bundle_target|
        resource_bundle_target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end

    # --- Apple/Xcode optimization: pre-populate Hermes during pod install, no-op the phase at build time ---
    ios_root = Pod::Config.instance.installation_root
    pods_root = File.join(ios_root, 'Pods')
    react_native_path = File.expand_path('../node_modules/react-native', ios_root)
    hermes_script = File.join(react_native_path, 'sdks/hermes-engine/utils/replace_hermes_version.js')
    if File.file?(hermes_script)
      system('node', hermes_script, '-c', 'Release', '-r', '0.76.3', '-p', pods_root, chdir: ios_root)
    end
    installer.pods_project.targets.each do |target|
      if target.name == 'hermes-engine'
        target.build_phases.each do |phase|
          if phase.respond_to?(:name) && phase.name && phase.name.include?('[Hermes] Replace Hermes')
            phase.shell_path = '/bin/bash'
            phase.shell_script = 'exit 0'
            break
          end
        end
        break
      end
    end

    # Fix paths with spaces: quote paths in script phases so "dribling madness for wardlaw" works
    installer.pods_project.targets.each do |target|
      target.build_phases.each do |phase|
        next unless phase.respond_to?(:shell_script) && phase.shell_script
        script = phase.shell_script
        if script.include?('WITH_ENVIRONMENT') && script.include?('SCRIPT_PHASES_SCRIPT')
          phase.shell_script = script.sub('"$WITH_ENVIRONMENT $SCRIPT_PHASES_SCRIPT"', '"\"$WITH_ENVIRONMENT\" \"$SCRIPT_PHASES_SCRIPT\""')
        elsif script.include?('get-app-config-ios.sh')
          phase.shell_script = 'bash -l -c "\"$PODS_TARGET_SRCROOT/../scripts/get-app-config-ios.sh\""'
        end
      end
    end
  end
end
